# Tell Sonar to look at everything in the root
sonar.sources=.

# Specifically tell it NOT to ignore the xcodeproj folder
sonar.inclusions=**/*.swift,**/*.pbxproj

# Ensure the Secrets engine scans text files
sonar.text.inclusions=**/*.pbxproj
