# Basic project info
sonar.projectKey=RafikOrg_trackeriOSApp
sonar.projectName=trackeriOSApp

# Force Sonar to index the root directory
sonar.sources=.

# Specifically include the pbxproj file
sonar.inclusions=**/*.swift, **/*.pbxproj

# Tell Sonar to treat pbxproj as text for Secret Scanning
sonar.text.inclusions=**/*.pbxproj
